[package]
name = "rcu_cell"
description = "a lockless rcu cell implementation"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
categories = ["non-blocking", "rcu", "atomic", "lock-free"]
keywords = ["rcu", "lockless", "atomic"]
repository = "https://github.com/Xudong-Huang/rcu_cell"
license = "LGPL-3.0"
readme = "./README.md"
version = "0.1.0"

[badges]
travis-ci = { repository = "Xudong-Huang/rcu_cell" }
